# Generated by Django 2.0 on 2019-07-28 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=1000, verbose_name='Job title')),
                ('location', models.CharField(max_length=1000, verbose_name='Country')),
                ('workers', models.PositiveIntegerField(default=0, verbose_name='No. of workers')),
                ('city', models.CharField(max_length=1000, verbose_name='City')),
                ('wage', models.PositiveIntegerField(default=0, verbose_name='Wage')),
                ('work_hours', models.PositiveIntegerField(default=0, verbose_name='No. of working hours')),
                ('overtime', models.PositiveIntegerField(default=0, verbose_name='Overtime')),
                ('accomodation', models.CharField(max_length=1000, verbose_name='Accomodation')),
                ('medical', models.CharField(max_length=1000, verbose_name='Medical insurance')),
                ('transport', models.CharField(max_length=1000, verbose_name='Tansport')),
                ('age_male_min', models.PositiveIntegerField(default=18, validators=[django.core.validators.MinValueValidator(18)], verbose_name='Male minimum age')),
                ('age_male_max', models.PositiveIntegerField(default=0, verbose_name='Male maximum age')),
                ('age_female_min', models.PositiveIntegerField(default=18, validators=[django.core.validators.MinValueValidator(18)], verbose_name='Female minimum age')),
                ('age_female_max', models.PositiveIntegerField(default=0, verbose_name='Female maximum age')),
                ('educ_level', models.CharField(max_length=1000, verbose_name='Minimum educ_level')),
                ('job_desc', models.TextField(default='Job Description', max_length=2000, verbose_name='Job description')),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('job_exp_date', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='gallery')),
                ('album', models.CharField(choices=[('Interviews', 'Interviews'), ('Departures', 'Departures'), ('Briefings', 'Briefings'), ('At work', 'At work')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms')], max_length=5)),
                ('firstName', models.CharField(max_length=100)),
                ('surName', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('maritalStatus', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('passportNo', models.PositiveIntegerField()),
                ('tel', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('birthPlace', models.CharField(max_length=200, verbose_name='District of birth')),
                ('county', models.CharField(max_length=100)),
                ('subCounty', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('residence', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=200)),
                ('academic', models.CharField(max_length=500)),
                ('spouse', models.CharField(blank=True, max_length=100)),
                ('children', models.PositiveIntegerField(blank=True)),
                ('fathersName', models.CharField(max_length=100)),
                ('mothersName', models.CharField(max_length=100)),
                ('parentsDistrict', models.CharField(max_length=100)),
                ('parentsTel', models.PositiveIntegerField(blank=True)),
                ('kin', models.CharField(max_length=100)),
                ('kinDistrict', models.CharField(max_length=100)),
                ('kinTel', models.PositiveIntegerField()),
                ('reg_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img_profile', models.FileField(blank=True, upload_to='media/gallery/profile')),
                ('occupation', models.CharField(max_length=100)),
                ('testimonial_desc', models.TextField()),
                ('testmnl_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YouTube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vidurl', models.URLField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
